version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: Sintaxis_php
            MYSQL_PASSWORD: ragnarok
            MYSQL_ROOT_PASSWORD:  ragnarok
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            -  persistent:/var/lib/mysql
        networks:
            - default
    web:
        build: .
        ports: 
            - "81:80"
        volumes:
            - ./html:/var/www/html
        links:
            - db
        networks:
            - default  
volumes:
    persistent:
